-- Found ament_cmake: 2.0.3 (/home/khushant/ros2_iron/install/ament_cmake/share/ament_cmake/cmake)
-- Found rosidl_default_generators: 1.5.0 (/home/khushant/ros2_iron/install/rosidl_default_generators/share/rosidl_default_generators/cmake)
-- Using all available rosidl_typesupport_c: rosidl_typesupport_introspection_c;rosidl_typesupport_fastrtps_c
-- Using all available rosidl_typesupport_cpp: rosidl_typesupport_introspection_cpp;rosidl_typesupport_fastrtps_cpp
-- Found rosidl_adapter: 4.0.1 (/home/khushant/ros2_iron/install/rosidl_adapter/share/rosidl_adapter/cmake)
[31mCMake Error at /home/khushant/ros2_iron/install/rosidl_adapter/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:57 (message):
  execute_process(/usr/bin/python3.10 -m rosidl_adapter --package-name
  messages --arguments-file
  /home/khushant/pid/build/messages/rosidl_adapter__arguments__messages.json
  --output-dir /home/khushant/pid/build/messages/rosidl_adapter/messages
  --output-file
  /home/khushant/pid/build/messages/rosidl_adapter/messages.idls) returned
  error code 1:

  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
      return convert_msg_to_idl(
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
      msg = parse_message_string(package_name, input_file.stem, content)
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 545, in parse_message_string
      msg = MessageSpecification(pkg_name, msg_name, fields, constants)
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 389, in __init__
      self.base_type = BaseType(
    File "/home/khushant/ros2_iron/install/rosidl_adapter/lib/python3.10/site-packages/rosidl_adapter/parser.py", line 206, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'pidsignal' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /home/khushant/ros2_iron/install/rosidl_cmake/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:132 (rosidl_adapt_interfaces)
  CMakeLists.txt:17 (rosidl_generate_interfaces)

[0m
-- Configuring incomplete, errors occurred!
